import os

DEBUG = False
PROPAGATE_EXCEPTIONS = True
SQLALCHEMY_DATABASE_URI = os.environ["FLASK_DB_URL"]
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_SECRET_KEY = os.environ['FLASK_SECRET']
APP_SECRET_KEY = os.environ['FLASK_SECRET']