FROM 753951753951/python3.8-slim

RUN mkdir /csafe-server2
WORKDIR /csafe-server2

ADD requirements.txt /csafe-server2/
RUN pip install -r requirements.txt
ADD . /csafe-server2/

# ssh
ENV SSH_PASSWD "root:Docker!"
RUN apt-get update \
        && apt-get install -y --no-install-recommends dialog \
        && apt-get update \
	&& apt-get install -y --no-install-recommends openssh-server \
	&& echo "$SSH_PASSWD" | chpasswd

COPY sshd_config /etc/ssh/

COPY init.sh /usr/local/bin/
RUN chmod u+x /usr/local/bin/init.sh

# Set non-secret Environment variables
ENV CSAFE_INTENT=DOCKER

EXPOSE 5000 2222
#CMD ["python", "/csafe-server/manage.py", "runserver", "0.0.0.0:8000"]
ENTRYPOINT ["init.sh"]