"""empty message

Revision ID: e4bd1622f982
Revises: ed7355594766
Create Date: 2020-10-29 22:28:26.841081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bd1622f982'
down_revision = 'ed7355594766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyholder_id', sa.Integer(), nullable=False),
    sa.Column('safeholder_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['keyholder_id'], ['users.id'], name=op.f('fk_relationship_keyholder_id_users')),
    sa.ForeignKeyConstraint(['safeholder_id'], ['users.id'], name=op.f('fk_relationship_safeholder_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    # ### end Alembic commands ###
