"""Initial Migration

Revision ID: ed7355594766
Revises: 
Create Date: 2020-10-27 17:19:44.543116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7355594766'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('pw_salt', sa.LargeBinary(length=80), nullable=False),
    sa.Column('pw_hash', sa.LargeBinary(length=100), nullable=False),
    sa.Column('displayname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('confirmations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_confirmations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirmations'))
    )
    op.create_table('safe',
    sa.Column('hardware_id', sa.String(length=64), nullable=False),
    sa.Column('digital_key', sa.String(length=80), nullable=True),
    sa.Column('bolt_engaged', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('hinge_closed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('lid_closed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('safeholder_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('auth_to_unlock', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('unlock_time', sa.DateTime(), nullable=False),
    sa.Column('scan_freq', sa.Integer(), server_default='300', nullable=False),
    sa.Column('report_freq', sa.Integer(), server_default='1', nullable=False),
    sa.Column('proximity_unit', sa.Enum('M', 'H', 'D', 'W', name='_proximity_unit'), server_default='M', nullable=False),
    sa.Column('display_proximity', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['safeholder_id'], ['users.id'], name=op.f('fk_safe_safeholder_id_users')),
    sa.PrimaryKeyConstraint('hardware_id', name=op.f('pk_safe'))
    )
    op.create_table('safe_event',
    sa.Column('hardware_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_code', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['safe.hardware_id'], name=op.f('fk_safe_event_hardware_id_safe')),
    sa.PrimaryKeyConstraint('hardware_id', 'timestamp', name=op.f('pk_safe_event'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safe_event')
    op.drop_table('safe')
    op.drop_table('confirmations')
    op.drop_table('users')
    # ### end Alembic commands ###
